# Generated by Django 3.1.6 on 2022-03-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_reg_app', '0003_auto_20220120_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_ride_distance',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.CharField(default='beginner', max_length=64),
        ),
    ]
