# Generated by Django 3.1.6 on 2022-03-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_and_reg_app', '0004_auto_20220301_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ridetitle', models.CharField(max_length=60)),
                ('startingpoint', models.CharField(max_length=100)),
                ('routefile', models.FileField(default=None, upload_to='rides/routefiles')),
                ('distance', models.CharField(max_length=10)),
                ('dateofride', models.DateField()),
                ('skill', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('ride_start_time', models.CharField(max_length=20)),
                ('est_end_time', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ridescreated', to='login_and_reg_app.user')),
                ('rides_joined', models.ManyToManyField(related_name='myrides', to='login_and_reg_app.User')),
                ('users_joined', models.ManyToManyField(related_name='usersriding', to='login_and_reg_app.User')),
            ],
        ),
    ]
