# Generated by Django 3.1.6 on 2022-03-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_reg_app', '0004_auto_20220301_2052'),
        ('BikeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='rides_joined',
            field=models.ManyToManyField(related_name='myrides', to='login_and_reg_app.User'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='routefile',
            field=models.FileField(default='No file uploaded', upload_to='rides/routefiles'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='users_joined',
            field=models.ManyToManyField(related_name='usersriding', to='login_and_reg_app.User'),
        ),
    ]
